version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: ict_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ict_skill_test
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345678"
      MYSQL_INNODB_BUFFER_POOL_SIZE: 1G
      MYSQL_MAX_CONNECTIONS: 200
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
