version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: ict_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ict_skill_reco
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ict-api:
    build: .
    container_name: ict_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://user:12345678@mysql:3306/ict_skill_reco"

volumes:
  mysql_data:
